Repository FarmSystem3th/Rangers-BE, pull requests merged in 2024-08, with the labels that each got.

#3 📝 [Docs] - template 작성
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/✨-feature-request.md
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/dongguk/rangers/RangersApplication.java
Labels: :memo: docs

#9 👷 [CI] CI/CD test용
  README.md
Labels: :construction_worker: ci

#10 👷 [CI] action 조건 수정
  .github/workflows/main.yml
Labels: :construction_worker: ci

#11 🐛 [Fix] username 수정
  .github/workflows/main.yml
Labels: :bug: bug

#12 🐛 [FIX] entry.sh 추가
  .github/workflows/main.yml
Labels: :bug: bug

#17 📝 [DOCS] trigger 조건 수정
  .github/workflows/main.yml
Labels: :memo: docs
